// <auto-generated />
namespace Prufa3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product));
        
        string IMigrationMetadata.Id
        {
            get { return "201405080031449_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
